//-------------------------------------------------------------------------
//                         DuckDB
//
//
// duckdb/common/enums/metrics_type.hpp
// 
// This file is automatically generated by scripts/generate_metric_enums.py
// Do not edit this file manually, your changes will be overwritten
//-------------------------------------------------------------------------

#pragma once

#include "duckdb/common/constants.hpp"

namespace duckdb {

enum class ModelType : uint8_t {
    TABULAR,
    LLM,
    GNN
};

} // namespace duckdb
